name: watts_my_bill
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  shadcn_ui: ^0.4.5

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Avenir Next
      fonts:
        - asset: assets/fonts/AvenirNext-Regular.ttf
          weight: 400
        - asset: assets/fonts/AvenirNext-Medium.ttf
          weight: 500
        - asset: assets/fonts/AvenirNext-DemiBold.ttf
          weight: 600
        - asset: assets/fonts/AvenirNext-Bold.ttf
          weight: 700
