name: watts_my_bill
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

fonts:
  - family: Avenir Next
    fonts:
      - asset: fonts/AvenirNext-Bold.ttf
        weight: 700
      - asset: fonts/AvenirNext-DemiBold.ttf
        weight: 600
      - asset: fonts/AvenirNext-Medium.ttf
        weight: 500
      - asset: fonts/AvenirNext-Regular.ttf
        weight: 400
